In [2]:
my_list = [1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones(4)

array([1., 1., 1., 1.])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.rand(5)

array([0.41876858, 0.67568319, 0.05253886, 0.48664447, 0.96513721])

In [22]:
np.random.rand(5,5)

array([[0.32419865, 0.63402094, 0.11626656, 0.51687916, 0.96378283],
       [0.85305014, 0.84726414, 0.68128826, 0.70917817, 0.37841656],
       [0.48997814, 0.57820324, 0.70889772, 0.22035372, 0.74891303],
       [0.90618955, 0.79131847, 0.90618396, 0.02896674, 0.96923793],
       [0.24210084, 0.75200963, 0.56332103, 0.15774261, 0.77513519]])

In [26]:
np.random.randint(1,100, 17)

array([96, 64, 94, 92, 87, 53, 96, 69, 17, 12, 29, 30, 48, 55, 23, 71, 83])

In [28]:
arr = np.arange(25)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
ranarr = np.random.randint(0, 50, 10)

In [31]:
ranarr

array([37, 11,  9, 29, 24, 25, 26, 17, 38, 21])

In [32]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
ranarr.max()

38

In [34]:
ranarr.min()

9

In [35]:
ranarr.argmax()

8

In [36]:
ranarr.argmin()

2

In [37]:
arr.shape

(25,)

In [38]:
arr2=arr.reshape(5,5)

In [40]:
arr2.shape

(5, 5)

In [41]:
arr.dtype

dtype('int32')

In [42]:
from numpy.random import randint 

In [43]:
randint(2,10)

4